default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: db/development/public_portfolio

test:
  <<: *default
  database: db/test/public_portfolio

production:
  <<: *default
  database: db/production
